In [4]:
import numpy as np

In [5]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
arr.shape

(3, 4)

In [8]:
#accessing specific elements of 2 d array -array[rows,column
arr[1,3]

8

In [9]:
arr[:,3]

array([ 4,  8, 12])

In [10]:
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr[:,3]

array([ 4,  8, 12])

In [13]:
arr[:,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [14]:
arr[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [15]:
arr[0:1,1:4]

array([[2, 3, 4]])

In [16]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [17]:
#creating all )s matrix
a=np.zeros((3,4),dtype="int64")

In [18]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
b=np.zeros((3,4),dtype="float")

In [20]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
c=np.zeros((3,4))

In [22]:
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
#creating all 1s index

In [24]:
a1=np.ones((4,5),dtype="int32")

In [25]:
print(a1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [26]:
a1[:,0:3]=10

In [27]:
print(a1)

[[10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]
 [10 10 10  1  1]]


In [28]:
a1[0:2,3:5]=4

In [29]:
a1

array([[10, 10, 10,  4,  4],
       [10, 10, 10,  4,  4],
       [10, 10, 10,  1,  1],
       [10, 10, 10,  1,  1]])

In [30]:
c=np.full(a1.shape,99)#here we need to tell shape

In [31]:
c

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [32]:
d=np.full_like(c,50)#no need to give shape

In [33]:
print(d)

[[50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]]


In [34]:
n1=np.ones((3,3),dtype="int32")

In [35]:
print(n1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
n2=np.full_like(n1,2)

In [37]:
print(n2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [38]:
n3=n1+n2

In [39]:
print(n3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [40]:
n=n3*n2

In [41]:
print(n)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [42]:
ar2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [43]:
print(ar2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
ar2[1,0,1]#[row,row,column]

8

In [45]:
ar2[0,:,1:3]

array([[2, 3],
       [5, 6]])

In [46]:
ar2[1,1,0:2]

array([10, 11])

In [47]:
ar2[0,:,1:3]

array([[2, 3],
       [5, 6]])

In [48]:
ar2[:,:,1:3]#isme equal karke koi number bhi assign kar sakte

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [49]:
a3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
a4=a3.reshape(2,6)#reshaping or molding in simple language

In [51]:
print(a4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [52]:
a5=a3.reshape(2,3,2)#2*3*2=12elelements_

In [53]:
print(a5)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [54]:
#copying the array
x=a3.copy()
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [55]:
'''COPY vs VIEW'''
'''copy mai original mai change nahi aata hai par view karne pe dono mai changes aate hai'''
x[3:6]=10 

In [56]:
print(x)

[ 1  2  3 10 10 10  7  8  9 10 11 12]


In [57]:
print(a3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [58]:
y=a3.view()
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [59]:
y[4:10]=99
print(y)

[ 1  2  3  4 99 99 99 99 99 99 11 12]


In [60]:
print(a3)

[ 1  2  3  4 99 99 99 99 99 99 11 12]


In [61]:
'''Iterating array's elements'''
for i in a3:
    print(i)

1
2
3
4
99
99
99
99
99
99
11
12


In [62]:
for i in a3:
    print(i+2)

3
4
5
6
101
101
101
101
101
101
13
14


In [63]:
'''Iteration in 2-D array'''
z=a3.reshape(4,3)

In [64]:
print(z)

[[ 1  2  3]
 [ 4 99 99]
 [99 99 99]
 [99 11 12]]


In [65]:
for i in z:
    print(i)

[1 2 3]
[ 4 99 99]
[99 99 99]
[99 11 12]


In [66]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [67]:
c=np.concatenate((a,b),axis=0)

In [68]:
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [69]:
#joining 2-d array
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])

In [70]:
k=np.concatenate((x,y),axis=0)#axis=0 means rows
print(k)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [71]:
w=np.concatenate((x,y),axis=1)

In [72]:
print(w)#axis=1 for columns 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [73]:
#sorting an array
arr1=np.array([3,4,5,8,1,9,27,15,16,20])

In [74]:
arr2=np.sort(arr1)

In [75]:
print(arr2)

[ 1  3  4  5  8  9 15 16 20 27]


In [76]:
#sorting 2-d array

In [77]:
a=arr2.reshape(2,5)
print(a)

[[ 1  3  4  5  8]
 [ 9 15 16 20 27]]
