# Random Module

In [8]:
#numpy offers a random module to generate a random number

In [10]:
import numpy as np
from numpy import random

In [27]:
x=np.random.randint(100)#0 se 99 tak
print(x)

16


# Generating array of random number

In [30]:
a=np.random.randint(100,size=5)
print(a) 

[48 92 53 52 56]


In [32]:
a.sort()

In [34]:
print(a)

[48 52 53 56 92]


# Generating 2-D array using random

In [39]:
b=np.random.randint(100,size=(3,4))#np likhne ki jarurat nahi hai btw
print(b)

[[23 63 44 46]
 [72 67 65 24]
 [88  6 26 69]]


# Generating random float

In [44]:
c=random.rand()#range jarurat nahi hai
print(c)

0.6894584600752981


In [48]:
#generating random float
d=random.rand(5)#size = likhne ki jarurat nahi hai
print(d)

[0.6320648  0.15666014 0.16817183 0.45371191 0.05573999]


In [52]:
e=random.rand(3,4)
print(e)

[[0.9749317  0.70077175 0.21820302 0.91939239]
 [0.66041271 0.22635519 0.06223035 0.68501362]
 [0.89616169 0.94184134 0.39070225 0.2934293 ]]


In [54]:
f=random.rand(2,2,4)
print(f)

[[[0.47265923 0.77291708 0.25156641 0.03413652]
  [0.48875724 0.55485206 0.36918233 0.3881773 ]]

 [[0.16991471 0.03370128 0.74391437 0.80255084]
  [0.550839   0.21989271 0.08078448 0.72884674]]]


# Selecting a random number from given array

In [63]:
rand_num=random.choice([2,3,4,5,7,8])
print(rand_num)

7


In [69]:
color=['Red','Green','Blue','White','Black','Yellow','Pink','Violet']
select_color=random.choice(color)
print(select_color)

Black


In [71]:
security_breches=np.array([[0,5,1],[0,2,0],[1,1,2],[2,2,1],[0,0,0]])
print(security_breches)

[[0 5 1]
 [0 2 0]
 [1 1 2]
 [2 2 1]
 [0 0 0]]


In [73]:
security_breches.sum()#sabka sum ho jaega

17

In [77]:
print(security_breches.sum(axis=1))#sum of rows

[6 2 4 5 0]


In [83]:
print(security_breches.sum(axis=0))#sum of columns

[ 3 10  4]


In [91]:
print(security_breches.min(axis=1))

[0 0 1 1 0]


In [93]:
print(security_breches.min(axis=0))

[0 0 0]


In [99]:
#finding mean
print(security_breches.mean(axis=0))
print(security_breches.mean(axis=1))

[0.6 2.  0.8]
[2.         0.66666667 1.33333333 1.66666667 0.        ]


In [105]:
print(security_breches.sum(axis=0,keepdims=True))

[[ 3 10  4]]


In [107]:
print(security_breches.sum(axis=1,keepdims=True))# sum ke time rows ka axis 1 hai

[[6]
 [2]
 [4]
 [5]
 [0]]


# Multiplying by a scalar

In [113]:
array=np.array([[1,2,3],[4,5,6]])
array*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [115]:
array=np.array([[1,2,3],[4,5,6]])
array>2

array([[False, False,  True],
       [ True,  True,  True]])

In [120]:
array=np.array(["Numpy","is","awesome"])
len(array)>2

True

In [128]:
vectorized_len=np.vectorize(len)
vectorized_len(array)>2

array([ True, False,  True])