# PANDAS    

pandas ia a python library used for manipulation of data sets.It has functions for data analysis,manipulation,exploration and visualisation

In [33]:
import pandas as pd
import numpy as np
from random import shuffle

In [7]:
pd?

Type:        module
String form: <module 'pandas' from 'C:\\Users\\LENOVO\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\lenovo\anaconda3\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be 

In [9]:
pd.Series()#shift+tab

Series([], dtype: object)

In [17]:
s1=pd.Series([10,20,30],index=['x','y','z'])#nostalgic af
print(s1)

x    10
y    20
z    30
dtype: int64


In [20]:
type(s1)

pandas.core.series.Series

# DataFrame

In [23]:
pd.DataFrame

pandas.core.frame.DataFrame

In [39]:
marks = np.arange(61,91).reshape(6,5)
print(marks)

[[61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]
 [76 77 78 79 80]
 [81 82 83 84 85]
 [86 87 88 89 90]]


In [71]:
shuffle(marks)

In [37]:
print(marks)

[69 73 65 82 70 86 63 85 87 89 72 75 64 74 76 79 77 66 62 88 83 67 61 78
 90 71 68 80 81 84]


In [49]:
name=['nitin','manvi','kanika','sahil','uttam','prince']
subjects=['Hindi','English','Maths','Physics','Chemistry']

In [57]:
grade=pd.DataFrame(data=marks,index=name,columns=subjects)

In [59]:
grade

Hindi  English  Maths  Physics  Chemistry
nitin      61       62     63       64         65
manvi      66       67     68       69         70
kanika     71       72     73       74         75
sahil      76       77     78       79         80
uttam      81       82     83       84         85
prince     86       87     88       89         90

In [61]:
grade.head()

Hindi  English  Maths  Physics  Chemistry
nitin      61       62     63       64         65
manvi      66       67     68       69         70
kanika     71       72     73       74         75
sahil      76       77     78       79         80
uttam      81       82     83       84         85

In [63]:
grade.tail()

Hindi  English  Maths  Physics  Chemistry
manvi      66       67     68       69         70
kanika     71       72     73       74         75
sahil      76       77     78       79         80
uttam      81       82     83       84         85
prince     86       87     88       89         90

In [65]:
grade.head(3)

Hindi  English  Maths  Physics  Chemistry
nitin      61       62     63       64         65
manvi      66       67     68       69         70
kanika     71       72     73       74         75

In [67]:
grade.tail(3)

Hindi  English  Maths  Physics  Chemistry
sahil      76       77     78       79         80
uttam      81       82     83       84         85
prince     86       87     88       89         90

In [75]:
grade.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, nitin to prince
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Hindi      6 non-null      int32
 1   English    6 non-null      int32
 2   Maths      6 non-null      int32
 3   Physics    6 non-null      int32
 4   Chemistry  6 non-null      int32
dtypes: int32(5)
memory usage: 168.0+ bytes


In [79]:
grade.describe()'''Mast'''

Hindi    English      Maths    Physics  Chemistry
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   62.666667  63.666667  64.666667  65.666667  66.666667
std     2.581989   2.581989   2.581989   2.581989   2.581989
min    61.000000  62.000000  63.000000  64.000000  65.000000
25%    61.000000  62.000000  63.000000  64.000000  65.000000
50%    61.000000  62.000000  63.000000  64.000000  65.000000
75%    64.750000  65.750000  66.750000  67.750000  68.750000
max    66.000000  67.000000  68.000000  69.000000  70.000000

# Creating Data Frame using dictionary

In [89]:
dict={
    'Name':['Yogita','Divya','Shaina','Tanishq','Harsh','Aditya'],
    'Roll_no':[1001,1002,1003,1004,1005,1006],
    'Age':[19,19,18,19,20,20]
}

In [102]:
students=pd.DataFrame(dict)
print(students)

      Name  Roll_no  Age
0   Yogita     1001   19
1    Divya     1002   19
2   Shaina     1003   18
3  Tanishq     1004   19
4    Harsh     1005   20
5   Aditya     1006   20
